name: cardano-launcher Windows Tests

on: [push]

jobs:
  tests:
    runs-on: windows-2016
    name: Run tests on Windows
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: npm install
      - name: Fetch cardano-wallet
        shell: powershell
        run: |
          node scripts\download-hydra.js
          Get-ChildItem
          Expand-Archive -Force -Path "cardano-wallet-20*-win64.zip" -DestinationPath .
          Expand-Archive -Force -Path "cardano-wallet-*-deployments.zip" -DestinationPath deployments
          Get-ChildItem
          echo "::set-env name=CARDANO_NODE_CONFIGS::$Env:GITHUB_WORKSPACE\deployments"
      - run: npm test unit
      - run: npm test integration
      - run: npm test cli
        timeout-minutes: 15
