name: cardano-launcher Windows Tests

on: [push]

jobs:
  tests:
    runs-on: windows-2016
    name: Run tests on Windows
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: input-output-hk/cardano-node
          path: cardano-node
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: Fetch cardano-wallet-jormungandr
        shell: powershell
        run: |
          $url = "https://hydra.iohk.io/job/Cardano/cardano-wallet/cardano-wallet-jormungandr-win64/latest/download/1"
          $output = "cardano-wallet-jormungandr-win64.zip"
          Invoke-WebRequest -Uri $url -OutFile $output
          Expand-Archive -Force -LiteralPath $output -DestinationPath .
      - name: Fetch cardano-wallet-byron
        shell: powershell
        run: |
          $url = "https://hydra.iohk.io/job/Cardano/cardano-wallet/cardano-wallet-byron-win64/latest/download/1"
          $output = "cardano-wallet-byron-win64.zip"
          Invoke-WebRequest -Uri $url -OutFile $output
          Expand-Archive -Force -LiteralPath $output -DestinationPath .
          Get-ChildItem
      - name: Fetch cardano-wallet-byron config
        shell: powershell
        run: |
          echo "::set-env name=BYRON_CONFIGS::$Env:GITHUB_WORKSPACE\cardano-node\configuration"
          $url = "https://hydra.iohk.io/job/Cardano/cardano-wallet/cardano-wallet-byron-win64/latest/download/2"
          $output = "cardano-wallet-byron-configuration.zip"
          Invoke-WebRequest -Uri $url -OutFile $output
          Expand-Archive -Force -LiteralPath $output -DestinationPath byron_configs
          Get-ChildItem
          echo "::set-env name=BYRON_CONFIGS::$Env:GITHUB_WORKSPACE\byron_configs"
        continue-on-error: true
#      - run: npm install
#      - run: npm test
      - run: npm run test:cli
        timeout-minutes: 15
