name: cardano-launcher Windows Tests

on: [push]

jobs:
  tests:
    runs-on: windows-2016
    name: Run tests on Windows
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: Fetch cardano-wallet-jormungandr
        shell: powershell
        run: |
          $url = "https://hydra.iohk.io/job/Cardano/cardano-wallet/cardano-wallet-jormungandr-win64/latest/download/1"
          $output = "cardano-wallet-jormungandr-win64.zip"
          Invoke-WebRequest -Uri $url -OutFile $output
          Expand-Archive -Force -LiteralPath $output -DestinationPath .
      - name: Fetch cardano-wallet-shelley
        shell: powershell
        run: |
          $url = "https://hydra.iohk.io/job/Cardano/cardano-wallet/cardano-wallet-shelley-win64/latest/download/1"
          $output = "cardano-wallet-shelley-win64.zip"
          Invoke-WebRequest -Uri $url -OutFile $output
          Expand-Archive -Force -LiteralPath $output -DestinationPath .
          Get-ChildItem
      - name: Fetch cardano-node deployment configuration
        shell: powershell
        run: |
          $url = "https://hydra.iohk.io/job/Cardano/cardano-wallet/cardano-wallet-shelley-win64/latest/download/3"
          $output = "cardano-wallet-shelley-deployments.zip"
          Invoke-WebRequest -Uri $url -OutFile $output
          Expand-Archive -Force -LiteralPath $output -DestinationPath shelley_deployments
          Get-ChildItem
          echo "::set-env name=CARDANO_NODE_CONFIGS::$Env:GITHUB_WORKSPACE\shelley_deployments"
      - run: npm install
      - run: npm test unit
      - run: npm test integration
      - run: npm test cli
        timeout-minutes: 15
